### ISSUE TITLE
JSON rendering for scp is not clear

### ISSUE THREAD

**Issue by akonstantinov** [scitokens/scitokens.github.io#17]
According to Claims.md "When rendered in JSON, the value of the scp claim should be a a JSON list.". But there is no such JSON data type (see https://tools.ietf.org/html/rfc7159#section-5). Closest seems to be an array. But in that case examples are not correct. Like 

"scp": "read:/store write:/store/user/bbockelm"

should be 

"scp": [ "read:/store write:/store/user/bbockelm" ]

**Comment by jbasney** [comment]
Thanks @akonstantinov for noting this issue. I think it's related to #14. The scp claim has changed in revisions to https://tools.ietf.org/html/draft-ietf-oauth-token-exchange, and in the latest revision, it's been replaced by the scope claim, which is a space separated string.
